import assert from 'node:assert/strict';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import test from 'node:test';
import {
  readMigrations,
  runMigrationsWithClient,
  type Migration,
  type QueryClient,
} from './migrations.ts';

class FakeClient implements QueryClient {
  queries: Array<{ text: string; params?: readonly unknown[] }> = [];
  applied = new Map<string, string>();

  async query<T>(text: string, params?: readonly unknown[]) {
    this.queries.push({ text: compact(text), params });
    if (text.startsWith('SELECT id, checksum FROM schema_migrations')) {
      return {
        rows: [...this.applied.entries()].map(([id, checksum]) => ({ id, checksum })),
      } as T;
    }
    if (text.startsWith('INSERT INTO schema_migrations')) {
      this.applied.set(String(params?.[0]), String(params?.[2]));
    }
    return { rows: [] } as T;
  }
}

test('readMigrations returns sorted sql migrations with checksums', () => {
  const dir = mkdtempSync(join(tmpdir(), 'efd-migrations-'));
  try {
    writeFileSync(join(dir, '002_second.sql'), 'SELECT 2;\n');
    writeFileSync(join(dir, '001_first.sql'), 'SELECT 1;\n');
    writeFileSync(join(dir, 'notes.txt'), 'ignore me');

    const migrations = readMigrations(dir);
    assert.deepEqual(migrations.map(m => m.id), ['001_first', '002_second']);
    assert.equal(migrations[0].sql, 'SELECT 1;');
    assert.match(migrations[0].checksum, /^[a-f0-9]{64}$/);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test('runMigrationsWithClient applies pending migrations inside a transaction', async () => {
  const client = new FakeClient();
  const migrations: Migration[] = [
    { id: '001_existing', name: '001_existing.sql', checksum: 'same', sql: 'SELECT 1;' },
    { id: '002_new', name: '002_new.sql', checksum: 'newhash', sql: 'SELECT 2;' },
  ];
  client.applied.set('001_existing', 'same');

  const result = await runMigrationsWithClient(client, migrations);

  assert.deepEqual(result, { applied: ['002_new'], skipped: ['001_existing'] });
  assert.equal(client.queries.some(q => q.text === 'BEGIN'), true);
  assert.equal(client.queries.some(q => q.text === 'COMMIT'), true);
  assert.equal(client.applied.get('002_new'), 'newhash');
});

test('runMigrationsWithClient rejects checksum drift', async () => {
  const client = new FakeClient();
  client.applied.set('001_existing', 'oldhash');

  await assert.rejects(
    () => runMigrationsWithClient(client, [
      { id: '001_existing', name: '001_existing.sql', checksum: 'newhash', sql: 'SELECT 1;' },
    ]),
    /checksum changed/,
  );
  assert.equal(client.queries.some(q => q.text === 'ROLLBACK'), true);
});

test('library tables use numeric ids expected by route params', () => {
  const sql = readFileSync(resolve('src/db/migrations/0001_multi_tenant_foundation.sql'), 'utf8');

  assert.match(tableBlock(sql, 'saved_skill_plans'), /id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY/);
  assert.match(tableBlock(sql, 'saved_fits'), /id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY/);
  assert.match(tableBlock(sql, 'saved_fit_items'), /id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY/);
  assert.match(tableBlock(sql, 'doctrines'), /id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY/);
  assert.match(tableBlock(sql, 'saved_fits'), /source_public_fit_id bigint REFERENCES saved_fits\(id\)/);
  assert.match(tableBlock(sql, 'doctrines'), /source_public_doctrine_id bigint REFERENCES doctrines\(id\)/);
  assert.match(tableBlock(sql, 'doctrine_fits'), /doctrine_id bigint NOT NULL REFERENCES doctrines\(id\)/);
  assert.match(tableBlock(sql, 'doctrine_fits'), /fit_id bigint NOT NULL REFERENCES saved_fits\(id\)/);
});

function compact(value: string): string {
  return value.replace(/\s+/g, ' ').trim();
}

function tableBlock(sql: string, table: string): string {
  const match = new RegExp(`CREATE TABLE IF NOT EXISTS ${table} \\(([\\s\\S]*?)\\n\\);`).exec(sql);
  assert.ok(match, `missing table ${table}`);
  return match[1];
}
