import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import assert from 'node:assert/strict';
import test from 'node:test';

test('Fits v2 shell is routed and visible as a standalone app view', () => {
  const routes = readFileSync(resolve('web/src/app-routes.ts'), 'utf8');
  const app = readFileSync(resolve('web/src/App.tsx'), 'utf8');
  const controlPanel = readFileSync(resolve('web/src/components/ControlPanel.tsx'), 'utf8');
  const switchView = readFileSync(resolve('web/src/components/FitModeSwitch.tsx'), 'utf8');
  const fitsView = readFileSync(resolve('web/src/components/FitsView.tsx'), 'utf8');
  const fitsV2View = readFileSync(resolve('web/src/components/FitsV2View.tsx'), 'utf8');

  assert.match(routes, /view: 'fitsV2'/);
  assert.match(routes, /first === 'fits-v2'/);
  assert.match(routes, /first === 'fit-v2'/);
  assert.match(routes, /`\/fit-v2\/\$\{route\.fitId\}`/);
  assert.match(controlPanel, />Fits v2<\/button>/);
  assert.match(app, /view === 'fitsV2'/);
  assert.match(app, /<FitsV2View/);
  assert.doesNotMatch(switchView, /Fits v2/);
  assert.doesNotMatch(fitsView, /fits-v2/);
  assert.doesNotMatch(fitsView, /FitsV2View/);
  assert.match(fitsV2View, /eveship-shell/);
  assert.match(fitsV2View, /fitting-ring/);
  assert.match(fitsV2View, /Hull &amp; Fits/);
  assert.match(fitsV2View, /Hardware/);
  assert.match(fitsV2View, /Simulation History/);
  assert.match(fitsV2View, /searchFitItems/);
  assert.match(fitsV2View, /Search modules, drones, cargo/);
  assert.match(fitsV2View, /function saveEditor\(\)/);
  assert.match(fitsV2View, /quoteDraftFit/);
  assert.match(fitsV2View, /Refresh price/);
  assert.match(fitsV2View, /sendDraftFit/);
  assert.match(fitsV2View, /Copy EFT/);
  assert.match(fitsV2View, /Send Fit/);
  assert.match(fitsV2View, /All V/);
  assert.match(fitsV2View, /updateSkillProfile/);
  assert.match(fitsV2View, /Dogma engine/);
  assert.match(fitsV2View, /renderEditorToEft/);
  assert.match(fitsV2View, /hasEditorJson/);
});
